energy:
  element: 内向型(I) or 外向型(E)
  element_description: 内向型は一人での活動を好み、社会的な交流によってエネルギーを消耗する傾向があります。外向型はグループでの活動を好み、社会的な交流によって活力を得ます。外向型はリーダシップを発揮する傾向があります。
  initial_questions:
    - '最近どのようなことに興奮しましたか？'
    - '自分が急に有名になったとしたら、どのように感じますか？'
    - '複数人でチームを組む時、どのような役回りになることが多いですか？'
    - '複数人での食事会の後で、どのように感じることが多いですか？'
    - 'どのような休日を過ごすとリフレッシュできたように感じますか？'
mind:
  element: 直感型(N) or 観察型(S)
  element_description: 直感型は物事を想像力豊かで、深く考察することを好みます。全体像を捉えようとするのも直感型の特徴です。観察型は観測可能な事実と直接的な結果に重きをおく現実主義者です。とにかく手を動かすことを好みます。
  initial_questions:
    - '新しいことを学ぶときにどのようなプロセスを踏むことが多いですか？'
    - '過去の自分にアドバイスするなら、どんなことを話しますか？'
    - '初対面の相手と話すとき、どのような点が気になりますか？'
    - '子どもに名前を付けるとしたら、どのような点に注意しますか？'
    - '初見では意味が分からない映画などを見たときにどのように感じますか？'

nature:
  element: 思考型(T) or 感情型(F)
  element_description: 思考型は論理と客観性を重視し、感情より合理性で判断する傾向があります。一方感情型は共感や調和を大切にし、他者の幸福や自分の気持ちに基づいて意思決定する傾向があります。
  initial_questions:
    - '人生の重要な意思決定の際に決め手となるのは、どんなことですか？'
    - '人からアドバイスを求められたときに、どのような対応を取ることが多いですか？'
    - 'チームで作業する際に、どのような人間関係を好ましいと感じますか？'
    - '友達が大事な約束を守らなかったときに、どのような言葉をかけますか？'
    - '会議で意見が対立したときに、どのように立ち回りますか？'

tactics:
  element: 判断型(J) or 知覚型(P)
  element_description: 判断型は計画や構造、明確さに安心を覚え、責任や完了を重視する傾向があります。一方知覚型は柔軟性と機会を好み、不確実性を刺激に変える傾向があります。
  initial_questions:
    - '予算の大きな買い物をするとき、最終的にはどうのようにして判断することが多いですか？'
    - '友達からの急な誘いに対して、どのように感じますか？'
    - 'あなたが付いていきたくなるようなリーダーはどんな人ですか？'
    - '長期的なプロジェクトの中で追加的なタスクが生じた際にどのように対処しますか？'
    - 'どのような一日を過ごせれば、満足に感じますか？'

question_per_phase: 10
